### PR TITLE
package: rm buffer as dependency

### PR DESCRIPTION
**Pull request by dcousens**
@dominictarr - we wouldn't list it here would we? or?
We don't want to import https://github.com/feross/buffer/ unnecessarily

### CODE REVIEW

**Comment by dominictarr** [comment]
Oh, I think that was just so we could test the perf of the js stack in node without starting a browser. It shouldn't make a difference in practice, because if you require this from node you'll get `crypto` but leaving this in means you'll get exactly the same code when you run the tests.

Is there a better reason than that to merge?

**Comment by dcousens** [comment]
You're thinking of the `devDependencies`,  this is in `dependency`, an artifact from https://github.com/crypto-browserify/sha.js/pull/41 and I'm just fixing it,  but asking.

**Comment by dominictarr** [comment]
sure, but why would you run crypto-browserify in node except during dev?
all other times, you should just get `crypto` and use the core buffer module.

**Comment by dcousens** [comment]
@dominictarr we used `sha.js` recently to test mid-state injection for a performance example,  and I certainly didn't want to make it any slower than necessary.
But maybe that is a strange use case.

**Comment by dominictarr** [comment]
@dcousens I think the browserify buffer is actually not slower. I think I heard somewhere that changes in v8 at some point meant that they had to use TypedArrays in node Buffers anyway, so it's more or less the same.

**Comment by dominictarr** [comment]
A performance difference is also something we can easily measure!

**Comment by dominictarr** [comment]
oh hang on, with smaller inputs (near the start of the output) the difference is much bigger, prehaps because of the cost of allocating typed arrays? (which are zeroed?)

**Comment by dcousens** [comment]
Interesting!

Certainly I think I agree we could leave `Buffer` in the `package.json`,  as I can't think of any reasonable scenario where this wouldn't be used only in the browser anyway.

This situation is not true of https://github.com/crypto-browserify/pbkdf2 for example,  so I do wonder what might be the best path going forward in terms of applying these changes to other projects in https://github.com/crypto-browserify.

**Comment by dcousens** [comment]
I do also worry that locking down the `Buffer` version could lead to package rot in bundling,  but,  I guess that is SEMVER anyway...

**Comment by dcousens** [comment]
Closing in favour of https://github.com/crypto-browserify/sha.js/pull/45

**Pull request closed without merging**
